### PR TITLE
Adds vertical and horizontal sprite generation

### PR DESCRIPTION
**Pull request by ffflabs**
It adds the option to change the orientation of the generated sprite (it's in the options dialog)

### CODE REVIEW

**Comment by draeton** [comment]
amenadiel - Sorry, I'm just seeing this. I'll look over it tonight

**Comment by draeton** [comment]
This is good work and I very much appreciate it. I kind of let the project languish for a bit, but there's a completely revamped version coming soon. This option is incorporated

**Comment by ffflabs** [comment]
I'm happy to know my little contribution was useful

**Comment by draeton** [comment]
Check out the new version - http://draeton.github.com/stitches/
The vertical and horizontal options are in the settings menu

**Pull request closed without merging**
